language: node_js
node_js:
- 5.0.0
services:
- mongodb
addons:
  apt:
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
before_install:
- npm install -g bower
- npm install -g protractor@3.0.0
- sudo apt-get install ruby-full
- gem install compass --version ="1.0.3"
- gem install sass --version ="3.4.18"
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24
install:
- npm install
- bower install
- ./node_modules/protractor/bin/webdriver-manager update --standalone
- ./node_modules/protractor/bin/webdriver-manager start --standalone &
before_script:
- npm install grunt-cli -g
- npm start &
- sleep 5
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
script:
  npm test